"""add ai category suggestion fields

Revision ID: 9ba03cec4341
Revises: 86811a03974e
Create Date: 2026-09-30 13:50:32.532238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba03cec4341'
down_revision: Union[str, Sequence[str], None] = '86811a03974e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_suggested_category', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ai_category_confidence', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('final_category', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ai_category_approved', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tickets_final_category'), 'tickets', ['final_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_final_category'), table_name='tickets')
    op.drop_column('tickets', 'ai_category_approved')
    op.drop_column('tickets', 'final_category')
    op.drop_column('tickets', 'ai_category_confidence')
    op.drop_column('tickets', 'ai_suggested_category')
    # ### end Alembic commands ###
